source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'SDWebImage-SFImageMaker_Example' do
  pod 'SDWebImage-SFImageMaker', :path => '../'

  target 'SDWebImage-SFImageMaker_Tests' do
    inherit! :search_paths

    
  end
end
